### ISSUE TITLE
SyntaxError in athena/dataset.py

### ISSUE THREAD

**Issue by brunnerdan** [arabiaweather/athena#2]
Tried to run a situation like the searching example, ran into the following error:  
```
File "/usr/local/lib/python2.7/site-packages/athena/dataset.py", line 64
    def get(self, p: str):
                   ^
SyntaxError: invalid syntax
```

**Comment by KhaledSharif** [comment]
Hi Brunnerdan, thanks for your question! Type hinting in Python was introduced in Python 3.5. You seem to be trying to run Athena on a version of Python that predates 3.5. You can read more about type hinting [at this link](https://docs.python.org/3/library/typing.html).

**Comment by brunnerdan** [comment]
Yes. Still using 2.7. This is the first I've encountered on type hinting. Look as though it can be made backward-compatible:
https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code

**Comment by KhaledSharif** [comment]
Interesting article. I'll work on compatibility issues during the next few days and I'll hopefully report back here once I've solved them all. Thanks!

**Comment by brunnerdan** [comment]
Thanks!

**Comment by KhaledSharif** [comment]
Hi @brunnerdan, good news! [My last commit](https://github.com/arabiaweather/athena/commit/b0fa65ee26b97c0f07155225c5ed0171a4f846f3) adds Python 2.7 compatibility. I tested out [the basic example with Docker](https://github.com/arabiaweather/athena/tree/master/docker) and it worked well. Tell me if this fixes your issue and/or if you need anything else.

**Comment by brunnerdan** [comment]
Great! I'm occupied with another project right now, so I cannot test this. But if it worked for you in 2.7, it should be good.
